navbar:
  blog_title: JasonChan
  ground_glass: false
index:
  banner_img: https://www.dmoe.cc/random.php
  banner_img_height: 100
  slogan:
    text: JasonChan|Blog
post:
  banner_img: https://www.dmoe.cc/random.php
  banner_img_height: 70
  default_index_img: https://www.dmoe.cc/random.php
archive:
  banner_img: https://www.dmoe.cc/random.php
  banner_img_height: 80
  subtitle: null
category:
  banner_img: https://www.dmoe.cc/random.php
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: https://www.dmoe.cc/random.php
  banner_img_height: 80
  subtitle: null
about:
  banner_img: https://www.dmoe.cc/random.php
  banner_img_height: 80
  subtitle: null
  avatar: /img/avatar.png
  name: JasonChan
  intro: An elegant theme for Hexo
links:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
  items:
    - link: https://9941y.top/
      title: Sh1zuku的小屋
      intro: 唯爱与科技不可辜负
      avatar: https://i0.hdslb.com/bfs/face/fdf541600f120a2af1d910ac857364d0e2442a36.jpg
    - title: Fluid Repo
      intro: 主题 GitHub 仓库
      link: https://github.com/fluid-dev/hexo-theme-fluid
      avatar: /img/favicon.png
    - title: 暮雨千泷
      intro: 青天白日梦神仙
      link: https://www.myql.xyz
      avatar: https://cdn.jsdelivr.net/gh/leicancun/img@main/images/avatar.webp
